blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/JonMinton/glm-dashboard-explainer/discussions
    about: For general questions or discussion about GLM tutorials
